### ISSUE TITLE
Can only plant 9 plants

### ISSUE THREAD

**Issue by sliceofliferp** [DemmyDemon/esx_uteknark#11]
According to my players, you can only plant 9 at a time. I'm not sure why this is. I also set the timer for it to take an hour total and they're accomplishing it in half the time?

**Comment by DemmyDemon** [comment]
According to your players? Have you tested it yourself?

I've planted literally hundreds on the same server during testing. Using the admin cheat command to mass-plant for performance testing I've planted _a hundred thousand_ at one point. I've heard from server operators that have performance issues because there are _tens of thousands_ of plants actually planted by users. I've seen screenshots and videos from a great many users and server operators, and most screenshots have _at least 10_ plants in them, but often they are "brag shots" labeled things like "I planted 200 weed today!"

"Can only plant 9" needs a lot more information for me to investigate it.
Plants do not belong to any particular player once they are planted, so as the system exists today there is no such thing as a per-user limit. That means there is a limit of 9 plants _in total_ on your sever?

One hypothesis is that you have reduced the first growth stage so much in time that the plant dies off very quickly, and that the user manages to stuff only nine plants in the ground during that time?

Please elaborate on what you mean by "only 9 at a time" so I have something to investigate.

As for the "half the time", this is not unexpected. It has to do with soil quality.
https://github.com/DemmyDemon/esx_uteknark/blob/master/config.lua#L34-L53
If those settings are not working as expected, please open a separate issue for it.

**Comment by DemmyDemon** [comment]
I'm going to file this under "Not enough information to do anything"
