### ISSUE TITLE
No Spawn on Start AND Errors ! 

### ISSUE THREAD

**Issue by ChrisZo187** [DemmyDemon/esx_uteknark#31]
So we got 2 Erros and no Spawn after Restart :(

https://prnt.sc/evACpCFFXVDU 
This is Server start Error

https://prnt.sc/aJiwW3L-c5KX
Client Side Error

https://prnt.sc/_V9RT_Ni3fKT
The Table :)

**Comment by DemmyDemon** [comment]
You are running a resource called "Seaside_Weed", and are filing an issue here?
Bring it up with whomever modified the resource. Looks like the quadtree bounds are too small.

**Comment by ChrisZo187** [comment]
im just joined the team but ill change it to esx_uteknark, we modified nothing only the grow time ... what is the quadtree bound ?

**Comment by DemmyDemon** [comment]
Why would you change just the name? Is it to give the impression that you guys made the software, and not someone else?
That's fine, it's allowed within the license, but to then have the nerve to come here to file an issue is pretty damn arrogant.

[The quadtree bounds](https://github.com/DemmyDemon/esx_uteknark/blob/master/lib/cropstate.lua#L137) are the center, width, height and depth of the spacial octree that holds the location of the plants so the client doesn't have to distance check _every single one_ to know if it's within interaction range.

Since I made this, the map has grown, and there is one or more plants outside the bounds.  Extend them as needed.

If you're wondering how to make that modification, I suggest you add at least one programmer to your team. This is not a support forum.
