### ISSUE TITLE
Plants disappearing

### ISSUE THREAD

**Issue by FlamingChilly** [DemmyDemon/esx_uteknark#7]
Hi.
We are having an issue on our server where people tend to the weed plants, walk around a corner and come back to find it is gone.  There are no other players in sight and this tends to happen on stage 5 of the process.

We have tested on multiple locations, even on the golf course

**Comment by DemmyDemon** [comment]
If they go away and come back, does it load again?
Any information in the logs, server or client?
Does it always happen to the same people, or does it vary what people it happens to?

**Comment by FlamingChilly** [comment]
Seems to be for several people.  We are testing it now again and also checking the console for errors.  Would a server restart affect the weed plants?  We clear our server cache on every restart

**Comment by FlamingChilly** [comment]
Then again, a clean cache shouldn't have any effect as the script writes the records to DB level.

**Comment by DemmyDemon** [comment]
Please answer the questions. If you don't, I really can't figure out the problem, and any fixes would be based on guesswork. I've been unable to reproduce the problem, so I need the information to figure out what the problem is. That's why I'm asking.
I'll try asking again, but in a more detailed way. There are a total of three questions, so please provide a total of three answers.

If the affected people walk away from where the plant is supposed to be (far away, not like 30 meters, more like a kilometer!) and go back, does the plant reappear?

Is there any information pertaining to UteKnark in the client log of the affected players, or in the server console?

Is it the same several people having this issue again and again, or does it seem to be random who can be affected?

To answer your question:
Server restarts remove the cache of the plants, so it has to load the plants from the database again. It should load **exactly the same** as it was before the restart, as steps are taken to store all the needed information and load it back to be the same. If it's not the same, then that's a bug.

Server cache, and the cleaning out of that cache, is irrelevant. I had a long rant about that typed up, but removed it as it's so deeply irrelevant to the issue at hand.

**Comment by FlamingChilly** [comment]
I will provide the three answers you are looking for in a short while, as I stated, we are busy testing the process again and gathering the results.

**Comment by FlamingChilly** [comment]
[CitizenFX_log_2020-02-10T093111.log](https://github.com/DemmyDemon/esx_uteknark/files/4180104/CitizenFX_log_2020-02-10T093111.log)

Attached is the CitizenFX Log file for one of the people who can't see the plants he planted last night, although I am standing right next to him and I see the plant.  No errors in the server console.

**Comment by FlamingChilly** [comment]
The issue happens to different players, and it seems to happen at Stage 5 of the process.

We moved away very far from the plants, and came back.  It still didn't show for them.

**Comment by DemmyDemon** [comment]
That log shows an absurd amount of broken models are being used on the server, and that you are overriding a whole lot of models from the server.

**What is the difference in system specs between you and the individual having problems?** It looks like the model isn't being loaded for them, but the game thinks it is, as it's _not_ producing the error message associated with not being able to load it.

The model for stages 5 and 6, `prop_weed_01`, is slightly more complex and draws with more aggressive LOD culling than the one for stages 1 through 4, `prop_weed_02`. Maybe the broken models being loaded, coupled with the sheer number of them, is causing the model budget to be spent before `prop_weed_01` can even be loaded?

If you don't care what the plant looks like, you can just change all occurrances of `plant_weed_01` to `plant_weed_02` in `lib/growth.lua`

Note that it is **more valuable for me to wait** for a complete response, than for you to post several half-baked responses. I'm more than happy to wait for a response until you actually have one, and there is no need to tell me what might happen at a later date. Just respond then instead.

Thank you.

**Comment by DemmyDemon** [comment]
Haven't heard anything about this issue in a long while, so I'm going to assume the last attempted fix was successful.
